name: Build Documentation

on: [push]

jobs:
  build_docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://pandoc/latex
    - name: Run a one-line script
      run: make docs
